name: mammos
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - git+https://github.com/MaMMoS-project/mammos-units.git
      - git+https://github.com/MaMMoS-project/mammos-entity.git
      - git+https://github.com/MaMMoS-project/mammos-dft.git
      - git+https://github.com/MaMMoS-project/mammos-spindynamics.git
      - git+https://github.com/MaMMoS-project/mammos-mumag.git
      
