name: mybinder-env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - bayesian-optimization
  - esys-escript=5.10
  - ubermag
  - uppasd
  - pip
  - trame-jupyter-extension
  - pip:
      - mammos==0.13.0
