name: mammos
channels:
  - conda-forge
dependencies:
  - python
  - esys-escript
  - oommf
  - pip
  - pip:
      - git+https://github.com/MaMMoS-project/mammos.git@main
      - pydantic>=2.11.5
      - ubermag

