name: Publish documentation

on:
  push:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: pandoc/actions/setup@v1
    - name: install dependencies
      run: pip install sphinx nbsphinx ipykernel pydata-sphinx-theme sphinx-copybutton sphinx-design .
    - name: build docs
      run: cd docs && make prepare && make html
    #- uses: prefix-dev/setup-pixi@v0.8.8
    #- run: pixi run docs
    - uses: actions/upload-pages-artifact@v3
      with:
        path: docs/build/html


  deploy:
    #if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/deploy-pages@v4
      id: deployment
